x-common-variables: &common-variables
  POSTGRES_USER: ${POSTGRES_USER:-admin}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
  POSTGRES_HOST: database
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_DB: ${POSTGRES_DB:-spotify}
  CLIENT_ID: ${CLIENT_ID}
  CLIENT_SECRET: ${CLIENT_SECRET}
  REDIRECT_URI: ${REDIRECT_URI:-"localhost:8080/callback"}
  SESSION_SECRET: ${SESSION_SECRET:-"secret phrase"}

services:

  website:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "cd /opt/ &&
             alembic upgrade head &&
             python -m uvicorn app.app:app --host 0.0.0.0 --port 8080 --reload"
    environment: *common-variables
    volumes:
      - type: bind
        source: ./app/
        target: /opt/app/
      - type: bind
        source: ./tests/
        target: /opt/tests/
      - type: bind
        source: ./alembic/
        target: /opt/alembic/
      - type: bind
        source: ./alembic.ini
        target: /opt/alembic.ini
      - type: bind
        source: ./.coveragerc
        target: /opt/.coveragerc

  database:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 2s
      retries: 5
      start_period: 2s
      timeout: 10s
    environment:
      <<: *common-variables
      POSTGRES_PORT: 5432
      POSTGRES_DB: spotify
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
