x-common-variables: &common-variables
  POSTGRES_USER: ${POSTGRES_USER:-admin}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
  POSTGRES_HOST: database
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_DB: ${POSTGRES_DB:-spotify}

services:

  website:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

    command: >
      sh -c "cd /opt/ &&
             alembic upgrade head &&
             python -m uvicorn app.app:app --host 0.0.0.0 --port 8080 --reload"
    environment: *common-variables

  database:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 2s
      retries: 5
      start_period: 2s
      timeout: 10s
    environment:
      <<: *common-variables
      POSTGRES_PORT: 543
      POSTGRES_DB: spotify
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
